/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class test_JniUtil */

#ifndef _Included_test_JniUtil
#define _Included_test_JniUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     test_JniUtil
 * Method:    get
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_test_JniUtil_get
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
